# Settings used throughout the script.
notification_emails: [test@test.com, test2@test.com]
threads: 1

# Default environmental variables.
API_KEY: # Defaults to "None" if it cannot be found in the environment.
FMS_API_URL: https://fmsdev.alliancegenome.org
SCHEMA_VERSION: 0.0.0
